[package]
name = "fusion-streamer-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
fusion-streamer = { path = "../.." }
eyre = "0.6.12"
tokio = { version = "1.41.1", features = ["full"] }
url = "2.5.4"
futures-util = "0.3.31"
dotenv = "0.15.0"
clap = { version = "4.4.18", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt"] }